### ISSUE TITLE
Feedback pour moi 

### ISSUE THREAD

**Issue by SamaraFellaDina** [koeenm/the-web-is-for-everyone-interactive-functionality#4]
### vormgeving
* Vormgeving ziet er goed uit. kan op sommige plekken alleen nog wat padding gebruiken.

![image](https://github.com/koeenm/the-web-is-for-everyone-interactive-functionality/assets/144009778/50a9d875-2b93-4b35-84bc-e59abaef9561)

* Heel vet! formuliertje? even traantje leggen zo goed. 
* verschillende pagina's aan de praat gekregen lekker bezig!
* Responsive? bravo

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExM2Z3cGxrdjg0MHo4bzM5c3U2M3h5ZTB0M2JqZWRzdjhheDM5bXZpciZlcD12MV9naWZzX3NlYXJjaCZjdD1n/hTgeSxaiyvYK4/giphy.gif)

#### [`server.js`](https://github.com/koeenm/the-web-is-for-everyone-interactive-functionality/blob/main/server.js)
* Is helemaal goed te begrijpen ook erg overzichtelijk

#### [`index.ejs`](https://github.com/koeenm/the-web-is-for-everyone-interactive-functionality/blob/main/views/index.ejs)
https://github.com/koeenm/the-web-is-for-everyone-interactive-functionality/blob/0217c67287c53fb0fecbd8f465c5b331b6ed66e4/views/index.ejs#L4-L8
* `section`? Een section begint met een heading, je zou moeten kijken of je dit element wilt vervangen met een `div` of een `article`

#### [`faq.ejs`](https://github.com/koeenm/the-web-is-for-everyone-interactive-functionality/blob/main/views/faq.ejs)
https://github.com/koeenm/the-web-is-for-everyone-interactive-functionality/blob/0217c67287c53fb0fecbd8f465c5b331b6ed66e4/views/faq.ejs#L17-L23

* Waarom maak je hier gebruik van `<style>`? Hiervoor heb je het [style.css](https://github.com/koeenm/the-web-is-for-everyone-interactive-functionality/blob/main/public/style.css) file voor

#### [`style.css`](https://github.com/koeenm/the-web-is-for-everyone-interactive-functionality/blob/main/public/style.css)
* `@font-face` moet altijd bovenaan. Dit is het allereerste wat je wilt importeren wanneer je een pagina opent. 

https://github.com/koeenm/the-web-is-for-everyone-interactive-functionality/blob/0217c67287c53fb0fecbd8f465c5b331b6ed66e4/public/style.css#L15-L17

* Je doet veel met css nesting, lekker bezig. Het enige wat ik nog zou meegeven is om eerste de basis elementen te stijlen. Je hebt bijvoorbeeld nu een stijlen voor een `h1` in een `header`, maar hoe ziet een `h1` op zichzelf eruit? Ik zou dat de volgende keer eerst stijlen, waarna je dus binnen die stijlen kan werken. Maar dan heb je teminste een goede basis. In mijn [`css`](https://github.com/SamaraFellaDina/the-web-is-for-everyone-interactive-functionality/blob/main/public/style.css#L41-L55) doe ik het ook al een beetje, maar zo zou je het misschien de volgende keer kunnen aanpakken. More DRY :) 
https://github.com/koeenm/the-web-is-for-everyone-interactive-functionality/blob/0217c67287c53fb0fecbd8f465c5b331b6ed66e4/public/style.css#L38-L51

* Misschien de `@media` op een plek zetten? Zet ze anders helemaal beneden, teminste als je een algemene verdeling wilt maken ervan. Maar dit is ook prima.

**Comment by koeenm** [comment]
dankjewel! ik heb verschillende dingen aangepast na deze issue:

Als eerste schreef je over de padding bij mijn formulier, een goed punt en dit heb ik gelijk verbeterd:

<img width=600 src="https://github.com/koeenm/the-web-is-for-everyone-interactive-functionality/assets/144009715/ef878234-22f2-42fb-9a7a-49ce470a5d44">

Hierna met een code foutje. Dit was een vrij lullige fout, omdat ik dit al meerdere keren heb gehoord:

#### [`index.ejs`](https://github.com/koeenm/the-web-is-for-everyone-interactive-functionality/blob/main/views/index.ejs)
https://github.com/koeenm/the-web-is-for-everyone-interactive-functionality/blob/0217c67287c53fb0fecbd8f465c5b331b6ed66e4/views/index.ejs#L4-L8
* `section`? Een section begint met een heading, je zou moeten kijken of je dit element wilt vervangen met een `div` of een `article`

Je suggereerde hier een div of een article element van te maken. En ik heb er een article element van gemaakt.

Ook heb ik iets gestyled in mijn html binnen een bepaalde partial. Ik heb dit gedaan omdat dit mijn handiger leek aangezien ik dit stukje styling alleen voor deze pagina nodig heb
